org: akaigamedev
app: ipa-to-audio
service: ipa-to-audio
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  ipa_to_audio:
    handler: handler.ipa_to_audio
    events:
      - httpApi:
          path: /
          method: post
